import glob
import os 
from pathlib import Path

def get_generate_paths(num_samples, rank, world_size, img_dir):
    """
    Determine which image indices should be generated by the current process.

    The full set of image indices is first partitioned across all processes
    using a strided assignment (i.e., `rank::world_size`). Any images that
    already exist in `img_dir` are then filtered out so generation can be
    resumed without duplicating work.

    Args:
        num_samples (Sequence or int):
            Collection whose length equals the total number of images to
            generate. Only `len(num_samples)` is used.
        rank (int):
            Rank of the current process.
        world_size (int):
            Total number of parallel processes.
        img_dir (str or Path):
            Directory containing generated PNG images. Images are expected
            to be named as `<index>.png`, where `<index>` is an integer.

    Returns:
        List[int]:
            Image indices assigned to the current process that have not yet
            been generated.
    """
    # All image indices.
    img_total_ids = [i for i in range(len(num_samples))]

    # Assign indices to this process via strided partitioning.
    img_total_ids = img_total_ids[rank::world_size]

    # Find existing generated images.
    exist_imgs = glob.glob(os.path.join(img_dir, "*.png"))
    img_idxs = [int(Path(i).stem) for i in exist_imgs]

    # Keep only images that still need to be generated.
    img_gen_idxs = [i for i in img_total_ids if i not in img_idxs]

    return img_gen_idxs

