import glob
import os 
from pathlib import Path
from torchvision.utils import save_image

def get_generate_paths(num_samples, rank, world_size, img_dir):
    """
    Determine which image indices should be generated by the current process.

    The full set of image indices is first partitioned across all processes
    using a strided assignment (i.e., `rank::world_size`). Any images that
    already exist in `img_dir` are then filtered out so generation can be
    resumed without duplicating work.

    Args:
        num_samples (int):
            Collection whose length equals the total number of images to
            generate. Only `len(num_samples)` is used.
        rank (int):
            Rank of the current process.
        world_size (int):
            Total number of parallel processes.
        img_dir (str or Path):
            Directory containing generated PNG images. Images are expected
            to have filenames beginning with the image index followed by an
            optional suffix, e.g., `<index>.png` or `<index>_*.png`.

    Returns:
        List[int]:
            Image indices assigned to the current process that have not yet
            been generated.
    """
    # All image indices.
    img_total_ids = [i for i in range(num_samples)]

    # Assign indices to this process via strided partitioning.
    img_total_ids = img_total_ids[rank::world_size]

    # Find indices of existing generated images. The image index is parsed
    # from the filename prefix before the first underscore (or the extension
    # if no underscore is present).
    exist_imgs = glob.glob(os.path.join(img_dir, "*.png"))
    img_idxs = [int(Path(i).stem.split("_")[0]) for i in exist_imgs]

    # Keep only images that still need to be generated.
    img_gen_idxs = [i for i in img_total_ids if i not in img_idxs]

    return img_gen_idxs

def save_img(sample_tensor, out_path_list):
    """
    Save a batch of images to disk.

    Each image in `sample_tensor` is saved to the corresponding file path in
    `out_path_list`. The input tensor is expected to have shape
    `[N, C, H, W]`, where `N` equals the number of output paths.

    Args:
        sample_tensor (torch.Tensor):
            Batch of images with shape `[N, C, H, W]`. The tensor may reside
            on either the CPU or GPU.
        out_path_list (Sequence[str | Path]):
            Output file paths for each image. Its length must match the batch
            size of `sample_tensor`.
    """
    # Ensure every image has a corresponding output path.
    assert len(out_path_list) == sample_tensor.size(0)

    # Move the batch to CPU before saving.
    sample_tensor = sample_tensor.cpu()

    # Save each image to its corresponding path.
    for _path, _tensor in zip(out_path_list, sample_tensor):
        save_image(_tensor, _path)
